### ISSUE TITLE
Überschriften bei showreg()

### ISSUE THREAD

**Issue by JonasSend** [skranz/regtools#1]
Mir ist gerade aufgefallen, dass ich ja auch auf deutsch schreiben kann =) Also wie gesagt, wäre es bei showreg() interessant, wenn man Überschriften auch im Screen-Output hinzufügen könnte.
-Gruß, Jonas

**Comment by skranz** [comment]
Good suggestion. I added the argument `title` to showreg that shows a title. Perhaps the layout can be improved at some point.
