### ISSUE TITLE
Installation failed with "ERROR: dependency ‘restorepoint’ is not available for package ‘regtools’

### ISSUE THREAD

**Issue by cdagnino** [skranz/regtools#2]
The dependency 'restorepoint' hasn't been available for CRAN for a few months now (see [here](https://cran.r-project.org/web/packages/restorepoint/index.html)). I resolved it by downloading the `.tar` and then manually installing `restorepoint`. Maybe you can consider removing that dependency?

**Comment by skranz** [comment]
Like regtools, restorepoint is now on github only. I have added a README.md with installation instructions.
